### ISSUE TITLE
Passwords not parsed correctly

### ISSUE THREAD

**Issue by pakux** [chrm-software/cryptmee#1]
Passwords /Passphrases containing special characters (space, etc.) might not be sent correctly to gpg.

In gnupgconnector.cpp on line 173:
   QString gpgIn = this->gpgBinaryPath + QString(" --batch --no-tty --yes --always-trust --passphrase ") + _passphrase + " -o " + TMPFILE + ".txt" + " --decrypt " + TMPFILE;

should be

QString gpgIn = this->gpgBinaryPath + QString(" --batch --no-tty --yes --always-trust --passphrase \"") + _passphrase + "\" -o " + TMPFILE + ".txt" + " --decrypt " + TMPFILE;

**Comment by chrm-software** [comment]
Thx! Will be included in 0.2.2.
